name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4

    - name: Build & Install Mono
      run: ./ci/install-mono.sh

    - name: Compile
      run: ./compile.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: HLTextureToolsCLI
        path: |
          ./bin/*
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        name: Continuous Build
        tag: continuous
        allowUpdates: false
        artifacts: HLTextureToolsCLI
